<a href="https://colab.research.google.com/github/luciusKrieguer/proyectoProfesionesIA/blob/master/Copia_de_la_copia_de_ProyectoAi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!pip install deep-translator

Requirement already satisfied: deep-translator in /usr/local/lib/python3.11/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.11/dist-packages (from deep-translator) (4.13.4)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from deep-translator) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.14.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2025.6.15)

In [10]:
#from google.colab import drive
#drive.mount('/content/DataSet_proyect.xlsx')

In [11]:
#from google.colab import drive
#drive.mount('/content/drive')

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from deep_translator import GoogleTranslator

In [13]:
df = pd.read_excel('DataSet_proyect.xlsx')
print(df.head())

   Sr.No.  Course Job profession Student  Linguistic  Musical  Bodily  \
0     1.0     NaN   Astronomer\n      S1          11        5      12
1     NaN     NaN   Astronomer\n      S2          12        6      12
2     NaN     NaN   Astronomer\n      S3          13        7      12
3     NaN     NaN   Astronomer\n      S4          14        8      12
4     NaN     NaN   Astronomer\n      S5          13        9      12

   Logical - Mathematical  Spatial-Visualization  Interpersonal  ...  \
0                      16                     17             11  ...
1                      16                     16             11  ...
2                      16                     15             11  ...
3                      16                     19             11  ...
4                      16                     20             11  ...

   Naturalist  s/p   P1    P2   P3    P4    P5   P6    P7    P8
0          19   s1  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST
1          19   s2  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST
2          19   s3  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST
3          19   s4  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST
4          19   s5  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST

[5 rows x 21 columns]

In [14]:
#a√±adimos columna del id al principio del df
df.insert(0, 'id', range(1, len(df)+1))
df

,id,Sr.No.,Course,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,...,Naturalist,s/p,P1,P2,P3,P4,P5,P6,P7,P8
0,1,1.0,NaN,Astronomer\n,S1,11,5,12,16,17,...,19,s1,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
1,2,NaN,NaN,Astronomer\n,S2,12,6,12,16,16,...,19,s2,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
2,3,NaN,NaN,Astronomer\n,S3,13,7,12,16,15,...,19,s3,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
3,4,NaN,NaN,Astronomer\n,S4,14,8,12,16,19,...,19,s4,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
4,5,NaN,NaN,Astronomer\n,S5,13,9,12,16,20,...,19,s5,AVG,POOR,AVG,BEST,BEST,AVG,BEST,BEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,3596,NaN,NaN,Technician,S3596,8,7,15,12,14,...,11,s3596,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3596,3597,NaN,NaN,Technician,S3597,9,8,16,11,13,...,12,s3597,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3597,3598,NaN,NaN,Technician,S3598,10,8,17,12,11,...,14,s3598,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3598,3599,NaN,NaN,Technician,S3599,6,9,19,13,13,...,11,s3599,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG
3599,3600,NaN,NaN,Technician,S3600,8,9,18,14,14,...,11,s3600,POOR,POOR,BEST,AVG,AVG,BEST,AVG,AVG

In [15]:
#Mostrar columnas
df.columns[:]

Index(['id', 'Sr.No.', 'Course', 'Job profession', 'Student', 'Linguistic',
       'Musical', 'Bodily', 'Logical - Mathematical', 'Spatial-Visualization',
       'Interpersonal', 'Intrapersonal', 'Naturalist', 's/p', 'P1', 'P2', 'P3',
       'P4', 'P5', 'P6', 'P7', 'P8'],
      dtype='object')

In [16]:
#Columnas que utilizaremos
cols_mantener = [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
df_new = df.iloc[:, cols_mantener]
df_new

,id,Course,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist
0,1,NaN,Astronomer\n,S1,11,5,12,16,17,11,18,19
1,2,NaN,Astronomer\n,S2,12,6,12,16,16,11,18,19
2,3,NaN,Astronomer\n,S3,13,7,12,16,15,11,18,19
3,4,NaN,Astronomer\n,S4,14,8,12,16,19,11,18,19
4,5,NaN,Astronomer\n,S5,13,9,12,16,20,11,19,19
...,...,...,...,...,...,...,...,...,...,...,...,...
3595,3596,NaN,Technician,S3596,8,7,15,12,14,15,14,11
3596,3597,NaN,Technician,S3597,9,8,16,11,13,16,14,12
3597,3598,NaN,Technician,S3598,10,8,17,12,11,17,14,14
3598,3599,NaN,Technician,S3599,6,9,19,13,13,18,13,11
3599,3600,NaN,Technician,S3600,8,9,18,14,14,19,14,11

In [17]:
df_new['Job profession'].unique()

array(['Astronomer\n', 'Geologist', 'Marine Biologist\n', 'Veterinarian',
       'Nature photographer', 'Recording engineer', 'Audiologist',
       'Sound editor', 'Music teacher', 'Actuary', 'Chartered Accountant',
       'Computer analyst', 'Computer programmer', 'Database designer',
       'Economist', 'Librarian', 'Engineer', 'Lawyer', 'Pharmacist',
       'Physician', 'Physicist', 'Mathematician', 'Leader', 'Manager',
       'Politician', 'Social Worker', 'Receptionist',
       'Sales Representative', 'Counselor', 'Athlete', 'Dancer',
       'Mechanic', 'Actor / Actress', 'Physical Therapist', 'Editor',
       'Historian', 'Journalist', 'Language Teacher', 'Poet',
       'Broadcaster', 'Artist', 'Graphic Designer', 'Fashion Designer',
       'Interior Decorator', 'Pilot', 'Psychologist', 'Philosopher',
       'Writer', 'Criminologist', 'Company secretary', 'Marketing',
       'Logistics manager', 'Research analyst', 'Business manager',
       'Internal auditor', 'Chief financial officer', 'Business Analyst',
       'Banking', 'Stock Broker', 'Financial Advisor', 'Consultant',
       'Archeologist', 'Pre Primary Teacher (2020 NEP and Mental Health)',
       'Primary Teacher', 'Middle, Higher School Teacher and Professors',
       'Anthropologist', 'Medical',
       'Para Medical (physiotherapy, occupational theropy, audio and speech language theropy, nursing)',
       'Militry',
       'Para Militry (https://en.wikipedia.org/wiki/Paramilitary_forces_of_India)',
       'Police Force (Spies, CBI officials, CID, Detectives)',
       'Technician'], dtype=object)

In [18]:
#Cambiar algunos nombres de los datos
df3 = df_new.replace(['Astronomer\n', 'Marine Biologist\n'], ['Astronomer', 'Marine Biologist'])
df3

,id,Course,Job profession,Student,Linguistic,Musical,Bodily,Logical - Mathematical,Spatial-Visualization,Interpersonal,Intrapersonal,Naturalist
0,1,NaN,Astronomer,S1,11,5,12,16,17,11,18,19
1,2,NaN,Astronomer,S2,12,6,12,16,16,11,18,19
2,3,NaN,Astronomer,S3,13,7,12,16,15,11,18,19
3,4,NaN,Astronomer,S4,14,8,12,16,19,11,18,19
4,5,NaN,Astronomer,S5,13,9,12,16,20,11,19,19
...,...,...,...,...,...,...,...,...,...,...,...,...
3595,3596,NaN,Technician,S3596,8,7,15,12,14,15,14,11
3596,3597,NaN,Technician,S3597,9,8,16,11,13,16,14,12
3597,3598,NaN,Technician,S3598,10,8,17,12,11,17,14,14
3598,3599,NaN,Technician,S3599,6,9,19,13,13,18,13,11
3599,3600,NaN,Technician,S3600,8,9,18,14,14,19,14,11

#Ver datos corregidos

In [19]:
df3['Job profession'].unique()

array(['Astronomer', 'Geologist', 'Marine Biologist', 'Veterinarian',
       'Nature photographer', 'Recording engineer', 'Audiologist',
       'Sound editor', 'Music teacher', 'Actuary', 'Chartered Accountant',
       'Computer analyst', 'Computer programmer', 'Database designer',
       'Economist', 'Librarian', 'Engineer', 'Lawyer', 'Pharmacist',
       'Physician', 'Physicist', 'Mathematician', 'Leader', 'Manager',
       'Politician', 'Social Worker', 'Receptionist',
       'Sales Representative', 'Counselor', 'Athlete', 'Dancer',
       'Mechanic', 'Actor / Actress', 'Physical Therapist', 'Editor',
       'Historian', 'Journalist', 'Language Teacher', 'Poet',
       'Broadcaster', 'Artist', 'Graphic Designer', 'Fashion Designer',
       'Interior Decorator', 'Pilot', 'Psychologist', 'Philosopher',
       'Writer', 'Criminologist', 'Company secretary', 'Marketing',
       'Logistics manager', 'Research analyst', 'Business manager',
       'Internal auditor', 'Chief financial officer', 'Business Analyst',
       'Banking', 'Stock Broker', 'Financial Advisor', 'Consultant',
       'Archeologist', 'Pre Primary Teacher (2020 NEP and Mental Health)',
       'Primary Teacher', 'Middle, Higher School Teacher and Professors',
       'Anthropologist', 'Medical',
       'Para Medical (physiotherapy, occupational theropy, audio and speech language theropy, nursing)',
       'Militry',
       'Para Militry (https://en.wikipedia.org/wiki/Paramilitary_forces_of_India)',
       'Police Force (Spies, CBI officials, CID, Detectives)',
       'Technician'], dtype=object)

##Traducir la base de datos del ingles a espa√±ol

In [ ]:
df3['Profesion'] = df3['Job profession'].apply(lambda x: GoogleTranslator(source='auto', target='es').translate(x))
print(df3)

In [ ]:
df3

In [ ]:
#Borrar columnas en ingles y reemplazar con la traduccion en espa√±ol
df4 = df3.drop(columns=['Job profession', 'Course', 'Student'])
df4

In [ ]:
#movemos la columna Profesion a la posici√≥n 2
col_mover = df4.pop('Profesion')
df4.insert(1, 'Profesion', col_mover)
df4

In [ ]:
#eliminamos espacios iniciales y finales
for i in range(1):
    df4.iloc[:,1] = df4.iloc[:,1].str.strip()
df4

#Investigar
- Maquina de soporte vectorial (SVM)
- Regresi√≥n Lineal
- Regresi√≥n Logistica

Buscar que informaci√≥n nos esta faltando para que el programa reconozca lo que necesitamos

In [ ]:
df4['Profesion'].unique()

#05 de Junio

In [ ]:
df4['Profesion'] = df4['Profesion'].replace({'Secretario de la compa√±√≠a': 'Secretario', 'Profesor previo a la primaria (2020 NEP y salud mental)': 'Profesor de primera infancia', 'Maestros y profesores de escuela secundaria': 'Profesor de secundaria',
                                             'Para Medical (fisioterapia, tertop√≠a ocupacional, audio y terop√≠a del lenguaje del habla, enfermer√≠a)': 'Paramedico', 'Milider√≠a': 'Militar',
                                             'Para Militer√≠a (https://en.wikipedia.org/wiki/paramilitary_forces_of_india)': 'Medico Militar', 'Fuerza policial (esp√≠as, funcionarios de CBI, CID, detectives)': 'Fuerzas Especiales'})

In [ ]:
df4 = df4.rename(columns = {'Linguistic' : 'Lengua Castellana',
 'Musical' : 'Artistica',
 'Bodily' : 'Educacion Fisica',
 'Logical - Mathematical' : 'Matem√°ticas',
 'Spatial-Visualization' : 'Dibujo T√©cnico',
 'Interpersonal' : 'Civica y Urbanidad',
 'Intrapersonal' : '√âtica y Valores',
 'Naturalist' : 'Ciencias Naturales'})

In [ ]:
df4['Profesion'].unique()

##Separamos el Dataset

In [ ]:
#librerias
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

In [ ]:
#identifiquemos nuestras variables

#variable predictora
X = df4.iloc[:,2:]
#variable a predecir
Y = df4['Profesion']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.7, random_state=42)

- Modelo Multiclase
- GaussianNB para modelo Binomial: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html
- LabelEconder para convertir palabras en n√∫meros: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
- En el modelo SMV buscar un algoritmo que soporte las clases (Profesiones) y (Materias) . . . Algoritmo que soporte muchas clases

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train, Y_train)

In [ ]:
Y_predic=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import  classification_report, confusion_matrix,accuracy_score

result= confusion_matrix(Y_test,Y_predic)
print(" Confusion Martrix: ")
print(result)


result1= classification_report(Y_test,Y_predic)
print("Classification Report: ",)
print (result1)


result2 = accuracy_score(Y_test,Y_predic)
print("Accuracy:",result2)

## Analisis exploratorio y Graficos

In [ ]:
# Simular un estudiante con valores existentes del ejemplo en las 8 inteligencias
nuevo_estudiante = [[11, 5, 12, 16, 17, 11, 18, 19]]
prediccion = classifier.predict(nuevo_estudiante)
print("Profesi√≥n sugerida para el nuevo estudiante:", prediccion[0])
result3 = accuracy_score(Y_test,Y_predic)
print(result3)

In [ ]:
#agregar estudiante nuevo
nuevo_estudiante = [[5,10 ,19 ,20 ,4 ,10 ,11 ,15 ]]
prediccion = classifier.predict(nuevo_estudiante)
print("Profesi√≥n sugerida para el nuevo estudiante:", prediccion[0])
result3 = accuracy_score(Y_test,Y_predic)
print(result3)

In [ ]:
#revision general de la infromacion del dataset
print(df4.info())

In [ ]:
#revision estadistica sobre los datos y la informacion que contiene el dataset
print(df4.describe())

In [ ]:
#Grafico estdudiantes vs notas

df4.hist(figsize=(12, 10), bins=10)
plt.suptitle("Distribuci√≥n de calificaciones por materias: ")
plt.tight_layout()
plt.show()


#en este grafico se muestra una distribucion en relacion

In [ ]:
#grafico de matriz de confusi√≥n
def plot_conf_matrix(result, color, labels):
    classes = ['Linguistic', 'Musical', 'Bodily', 'Logical - Mathematical', 'Spatial-Visualization', 'Interpersonal', 'Intrapersonal', 'Naturalist']
    df_result = pd.DataFrame(result, index=labels, columns=labels)
    plt.figure(figsize=(12,10)) #Ajusta el tama√±o seg√∫n n√∫mero de clases
    ax = sns.heatmap(df_result, annot=True, fmt='d', cmap=color)
    ax.set_xlabel('Predicho')
    ax.set_ylabel('Valores Reales')
    ax.set_title('Matriz de Confusi√≥n')
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)

#Llamar la funci√≥n
plot_conf_matrix(result, 'inferno', df4['Profesion'].unique())

In [ ]:
#convertir nota de escala 1-5 a escala 1-20, para facilitar la interacci√≥n con el usuario
def convertir_nota_5_a_20(nota_5):
    if not (1 <= nota_5 <= 5):
        raise ValueError("La nota debe estar entre 1 y 5, puede ser decimal")
    #Conversion lineal de la escala 1-5 a 1-20
    nota_20 = ((nota_5 -1) / 4) * 19 + 1
    return nota_20
lista_notas = []
lista_notas_5 = []
columnas = df4.columns[2:]
for j in columnas:
    lista_notas_5.append(input(f"Escribe tu nota {j}: "))
for item in lista_notas_5:
    lista_notas.append(convertir_nota_5_a_20(float(item)))
#nota = input("Escribe una nota: ")
#convertir_nota_5_a_20(float(nota))
#nota2 = input("Escribe una nota2: ")
#lista = [nota, nota2]
lista_notas

In [ ]:

df4 = df4.rename(columns = {'Linguistic' : 'Lengua Castellana',
 'Musical' : 'Artistica',
 'Bodily' : 'Educacion Fisica',
 'Logical - Mathematical' : 'Matem√°ticas',
 'Spatial-Visualization' : 'Dibujo T√©cnico',
 'Interpersonal' : 'Civica y Urbanidad',
 'Intrapersonal' : '√âtica y Valores',
 'Naturalist' : 'Ciencias Naturales'})
list(df4.columns)